seed: 42
lr: 0.001
gamma: 0.99
buffer_size: 50000
batch_size: 64
num_episodes: 2001
max_steps: 500
log_freq: 50
checkpoint:
  enabled: true
  resume: false
  path: "./checkpoints"
  mode: latest
checkpoint_freq: 1000

epsilon:
  start: 1.0
  end: 0.05
  decay: 0.995
