project: effortsim
entity: floly

seed: 42

# PPO hiperparametry
learning_rate: 0.0003        
gamma: 0.99                  
gae_lambda: 0.95             
eps_clip: 0.2                
entropy_coef: 0.01           
value_loss_coef: 0.5         
ppo_epochs: 15               
mini_batch_size: 128
learn_every: 5

num_episodes: 5000
max_steps: 500

log_freq: 100
wandb_id: "ppo_penalyty" #we can change it to function that combines some hyperparameters but for now i dont know which

checkpoint:
  enabled: true
  resume: true
  path: "./checkpoints_ppo_penalyty"
  # "latest" - all agents load their latest checkpoint, "shared" - all agents load the same shared checkpoint, "individual" - each agent loads a uniquely specified checkpoint

  # if shared   DONT USE THIS PLS
  #   shared_name: walker_X_checkpoint_ep100.pt
  #
  # if individual
  # individual_names:
  #   walker_0: walker_0_checkpoint_ep100.pt
  #   walker_1: walker_1_checkpoint_ep099.pt
  #   walker_2: walker_2_checkpoint_ep101.pt
  freq: 500
  mode: "latest"

