project: effortsim
entity: floly

lr: 0.001
gamma: 0.99
eps_start: 1.0
eps_end: 0.01
eps_decay: 0.995
buffer_size: 50000
batch_size: 64

num_episodes: 1000
max_steps: 500
target_update_freq: 10
log_freq: 100

checkpoint:
  enabled: true
  resume: true
  path: "./checkpoints"
  # "latest" - all agents load their latest checkpoint, "shared" - all agents load the same shared checkpoint, "individual" - each agent loads a uniquely specified checkpoint

  # if shared   DONT USE THIS PLS
  #   shared_name: walker_X_checkpoint_ep100.pt
  #
  # if individual
  # individual_names:
  #   walker_0: walker_0_checkpoint_ep100.pt
  #   walker_1: walker_1_checkpoint_ep099.pt
  #   walker_2: walker_2_checkpoint_ep101.pt

  mode: latest

checkpoint_freq: 500 

lazy_agents: []   
lazy_scaling: 0.5  