project: effortsim-ppo
entity: floly

agent: ppo


log_freq: 100

# Trening
num_episodes: 4000   
eval_episodes: 15       
max_steps: 700              

# Checkpointy
checkpoint:
  enabled: true
  path: checkpoints/ppo/optuna_sweep/
  freq: 100
  mode: latest

